require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  NewCops: disable
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - tmp/**
    - test/**
    - storage/**/*
    - public/*
    - lib/**

Layout/LineLength:
  Max: 150

Metrics/BlockLength:
  Exclude:
    - config/**/*
    - spec/**/*

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*

Style/Documentation:
  Enabled: false
