version: '3.7'
services:
  db:
    image: postgres:12.3
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - backend
  web:
    build: .
    ports:
      - "82:3000"
      # - "3000:3000"
    environment:
      RAILS_ENV: development
    env_file: .env
    depends_on:
      - db
    networks:
      - backend
    image: tomasalvarez13/e0-2022-1-tomasalvarez13
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/var/www/html
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/ssl/:/etc/nginx/ssl/
    networks:
      - backend

volumes:
  data:
    driver: local

networks:
  backend: